# How to update the env:
#
# conda activate taichi-dev
# conda env update --file conda-env.yaml --prune
# https://stackoverflow.com/a/43873901/12003165

name: taichi-dev
dependencies:
  - python=3.8
  - GitPython
  - Pillow
  - astor
  - colorama
  - decorator
  - dill
  - flask
  - matplotlib
  - numpy
  - psutil
  - pybind11
  - pytest
  - pytest
  - pytorch
  - scipy
  - setuptools
  - yapf
  - yapf
