# How to update the env:
#
# conda activate taichi
# conda env update --file conda-env.yaml --prune
# https://stackoverflow.com/a/43873901/12003165

name: taichi
dependencies:
  - python=3.8
  - setuptools
  - numpy
  - scipy
  - matplotlib
